version: "2.2"

services:
#    etcd:
#        image: quay.io/coreos/etcd
    pushgateway:
        image: prom/pushgateway
        ports:
            - 9091:9091

    alertmanager:
        image: prom/alertmanager
        volumes:
            - ./alertmanager/:/etc/alertmanager/
        ports:
            - 9093:9093

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--web.enable-lifecycle"
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus:/prometheus
        links:
            - alertmanager
            - pushgateway

    grafana:
        image: grafana/grafana
        links:
            - prometheus
        ports:
            - 3000:3000
    

volumes:
    prometheus: