version: "2.2"
services:
  zookeeper:
    image: "zookeeper:3.5"
    ports:
      - "2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
    networks:
      - kafka

  kafka:
    image: "wurstmeister/kafka:2.12-2.2.1"
    ports:
      - "9092"
    scale: 2
    env_file:
      - kafka.env
    depends_on:
      - zookeeper
    networks:
      - kafka

networks:
  kafka: