version: "2.2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
    networks:
      - spark

  spark-master:
    image: sinovast/spark
    command: start-master.sh
    environment: 
      SPARK_NO_DAEMONIZE: "true"
    ports:
      - "8080"
      - "7077"
    networks:
      - spark
    links:
      - mysql

  spark-slaver:
    image: sinovast/spark
    command: start-slave.sh spark://spark-master:7077
    environment:
      SPARK_NO_DAEMONIZE: "true"
    ports:
      - "8081"
      - "7077"
    scale: 1
    links:
      - spark-master
      - mysql
    depends_on:
      - spark-master
    networks:
      - spark

networks:
  spark: